### ISSUE TITLE
cmsnr client keeps pushing policy even though it hasn't changed

### ISSUE THREAD

**Issue by gamer22026** [hooksie1/cmsnr#12]
I have just one opapolicy, but the cmsnr client keeps thinking the policy has changed and constantly pushed out a new one to opa even though the policy has not changed. If you're no longer working on this, I understand.
```time="2022-11-08T21:48:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:49:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:50:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:51:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:52:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:53:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:54:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:55:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:56:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:57:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:58:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T21:59:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:00:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:01:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:02:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:03:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:04:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:05:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:06:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:07:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:08:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:09:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:10:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:11:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"
time="2022-11-08T22:12:50Z" level=info msg="found update for opa policy portfolios for deployment apisix"

**Comment by hooksie1** [comment]
I'll take a look. I haven't done anything with this for a while but I'll see what I can figure out.

**Comment by hooksie1** [comment]
So I ran a test locally and with the policies in the examples directory and I wasn't seeing any updates like that. Which version are you using? And could you deploy the test policies to see if it's policy related?

**Comment by hooksie1** [comment]
Ok, weird. I was just kind of able to replicate it. Can you check with the example policies and let me know if you see the same issue?

**Comment by gamer22026** [comment]
Will do. I'm on the latest version.

**Comment by gamer22026** [comment]
OK, very odd. Not doing it on your examples. I even applied my policy to the example testing deployment and works fine. Our use case is using apisix (with their opa plugin) coupled with cmsnr, so I have the apisix deployment injected with cmsnr. Works fine except for the every minute re-uploading the policy to opa because it thinks it's changed. Realistically what deployment is injected should have no bearing on whether cmsnr client sidecar thinks the opapolicy has changed so I a bit stumped. If the apisix opa plugin is somehow modifying the policy on the opa sidecar, would cmsnr see that as a change even though the actual Opopolicy yaml didn't? That's the only thing I can think of that might be happening.

**Comment by gamer22026** [comment]
FYI, just did a looping GET of the policy from the opa sidecar piped to sha256sum to see if the policy on the opa side was changing and it did not (over ~ 10 minute loop). The checksum remained the same. So there goes that theory.

**Comment by gamer22026** [comment]
Applied your example policy (mypolicy) to my apisix deployment and it exhibits the same behavior.
```
time="2022-11-14T16:33:28Z" level=info msg="found new opa policy mypolicy for deployment apisix"
time="2022-11-14T16:34:03Z" level=info msg="found update for opa policy mypolicy for deployment apisix"
time="2022-11-14T16:35:01Z" level=info msg="found update for opa policy mypolicy for deployment apisix"
time="2022-11-14T16:36:03Z" level=info msg="found update for opa policy mypolicy for deployment apisix"
```

**Comment by gamer22026** [comment]
Any way to get cmsnr to log what it thinks the changes are?

**Comment by gamer22026** [comment]
Closing this. I wiped out the cmsnr install (including crds) and reinstalled and the problem no longer happens. Thanks for the help!

**Comment by hooksie1** [comment]
Sorry, I just noticed the replies. Started a new job and have been really busy. Glad it worked for you! My only guess is something happened with the docker image not pulling in the most recent release for some reason. Anyway glad it's working!
