### ISSUE TITLE
opa sidecar uses latest-static but webooks are pinned to a specific version

### ISSUE THREAD

**Issue by gamer22026** [hooksie1/cmsnr#21]
There are[ breaking changes](https://github.com/open-policy-agent/opa/releases/tag/v0.59.0) coming to opa and the rego policy language.  I see that the injected sidecar uses latest-static as a version while the web-hooks are pinned to a specific version by go.mod. I'm worried that always using latest-static in the sidecar will cause errors if breaking changes are introduced. Is it possible to have the injected sidecar default to using the same opa version as configured in go.mod and/or make the version of the injected sidecar configurable? That way if an opa version did introduce breaking changes we could at least pin to a specific version (without having to download and recompile the source code).

**Comment by gamer22026** [comment]
Same with the cmsnr sidecar, always uses latest. Would be nice to specify an actual version to be injected

**Comment by hooksie1** [comment]
yeah this makes sense. I'll try to get a fix in soon for this.

**Comment by hooksie1** [comment]
Ok this should be added with #22. Let me know if you have any issues. You can specify the tags with `--opa-tag` and `--cmsnr-tag`

**Comment by gamer22026** [comment]
Meant to close this a ways back! Thanks for looking into that and producing a fix. Been working fine.
