### ISSUE TITLE
Deleting an opapolicies should delete the corresponding policy in the opa sidecar

### ISSUE THREAD

**Issue by gamer22026** [hooksie1/cmsnr#5]
If I create/modify an opapolicies yaml and apply it, it correctly creates/modifies the policy in the opa sidecar, however if I delete the opapolicies it does not remove the policy from the opa sidecar

**Comment by hooksie1** [comment]
Sorry for the delay, I'll be taking a look at this this week.

**Comment by hooksie1** [comment]
Ok this is fixed with v0.0.3
